---

- name: remove domain from blacklist
  lineinfile:
    path:  /opt/zimbra/conf/blacklist
    state: absent
    regexp: '{{ domain }}'

- name: remove domain from blacklist
  lineinfile:
    path:  /opt/zimbra/conf/amavisd.conf.in
    state: absent
    regexp: "'{{ domain }}'  => 10"

- name: Execute the command zmamavisdctl to restart the service
  command:  su - zimbra -c "zmamavisdctl restart"
  become: true
  become_method: sudo
  
