---

- name: Create file whitelist ownership, group and permissions
  file:
    path: /opt/zimbra/conf/whitelist
    owner: zimbra
    group: zimbra
    mode: '0644'
    state: touch


- name: Add a line to whitelist
  lineinfile:
    path: /opt/zimbra/conf/whitelist
    line: '{{ domain }}'
    create: yes


- name: Add a line to /opt/zimbra/conf/amavisd.conf.in
  lineinfile:
    path:  /opt/zimbra/conf/amavisd.conf.in
    regexp: "'^'fake1.com' => 10 '"
    insertafter: "'#'fake1.com' => 10 '" 
    line:  "'{{ domain }}'  => 10"

- name: Execute the command zmamavisdctl to restart the service
  command: zmamavisdctl restart
  become: true
  become_method: su
  become_user: zimbra


