---
- name: Add domain to spamassain filter  whitelist domain
  lineinfile:
    path:  /opt/zimbra/conf/salocal.cf.in 
    line:  "whitelist_from *{{ domain }}"
  
- name: Add domain to spamassain filter  block email 
  lineinfile:
    path:  /opt/zimbra/conf/salocal.cf.in 
    line:   whitelist_from  {{ email }}


- name: Add a line to /opt/zimbra/conf/amavisd.conf.in whitelist domain
  lineinfile:
    path:  /opt/zimbra/conf/amavisd.conf.in
    insertbefore: "'.dali.mx'  => -10.0,"
    line:  "'.{{ domain }}'  => 10.0,"


- name: Add a line to /opt/zimbra/conf/amavisd.conf.in whitelist email
  lineinfile:
    path:  /opt/zimbra/conf/amavisd.conf.in
    insertbefore: "'.dali.mx'  => -10.0,"
    line:  "'{{ email }}'  => 10.0,"



- name: Execute the command zmamavisdctl to restart the service
  command: su - zimbra -c "zmmtactl restart && zmamavisdctl restart"
  become: true
  become_method: sudo
 

