---

- name: Create whitelist and  blacklist files
  shell:  touch /opt/zimbra/conf/{whitelist,blacklist}

- name: Add a line to whitelist
  lineinfile:
    path: /opt/zimbra/conf/whitelist
    line:  {{ domain1 }}
    create: yes
  tags: whitelist

- name: Add a line to blacklist
  lineinfile:
    path: /opt/zimbra/conf/whitelist
    line:  {{ domain2 }}
    create: yes
  tags: blacklist


- name: Add a line to blacklist
  lineinfile:
    path:  /opt/zimbra/conf/amavisd.conf.in
    line:  read_hash(%whitelist_sender, '/opt/zimbra/conf/whitelist');
    create: yes
  tags: whitelist

- name: Add a line to blacklist
  lineinfile:
    path:  /opt/zimbra/conf/amavisd.conf.in
    line:  read_hash(%whitelist_sender, '/opt/zimbra/conf/blacklist');
    create: yes
  tags: blacklist
