---

- name: Create file blacklist ownership, group and permissions
  file:
    path: /opt/zimbra/conf/blacklist
    owner: zimbra
    group: zimbra
    mode: '0644'
    state: touch

- name: Add a line to blacklist
  lineinfile:
    path: /opt/zimbra/conf/blacklist
    line:  "{{ domain }}"
    create: yes
 
- name: Add a line to /opt/zimbra/conf/amavisd.conf.in
  lineinfile:
    path:  /opt/zimbra/conf/amavisd.conf.in
    insertafter: "'fake.com' => 10"
    line:  "'{{ domain }}'  => 10"


- name: Execute the command zmamavisdctl to restart the service
  command: zmamavisdctl restart
  become: true
  become_method: sudo
  become_user: zimbra

