---

- name: Create blacklist files
  shell:  touch /opt/zimbra/conf/{blacklist}

- name: Add a line to blacklist
  lineinfile:
    path: /opt/zimbra/conf/blacklist
    line:  {{domain}}
    create: yes
 
- name: Add a line to blacklist
  lineinfile:
    path:  /opt/zimbra/conf/amavisd.conf.in
    line:  read_hash(%whitelist_sender, '/opt/zimbra/conf/blacklist');
    create: yes

